---
- name: Check exists JDK directory
  stat: path='/usr/java/{{ jdk.version }}'
  register: is_jdk_directory
  tags: [ 'jdk' ]

- name: Download Oracle JDK
  get_url:
    url: '{{ jdk.url }}'
    dest: '/tmp/{{ jdk.file }}'
    mode: 0644
    validate_certs: no
    headers: 'Cookie: oraclelicense=accept-securebackup-cookie'
  when: not is_jdk_directory.stat.exists
  tags: [ 'jdk' ]

- name: Install Oracle JDK
  yum:
    name: '/tmp/{{ jdk.file }}'
    state: present
  when: not is_jdk_directory.stat.exists
  tags: [ 'jdk' ]

