---
- name: Check exists Open JDK directory
  stat: path='/usr/lib/jvm/java-{{ openjdk.version }}-openjdk'
  register: is_openjdk_directory
  tags: [ 'jdk' ]

- name: Install Open JDK
  yum: name='java-{{ openjdk.version }}-openjdk' state=latest
  with_items:
    - 'java-{{ openjdk.version }}-openjdk'
    - 'java-{{ openjdk.version }}-openjdk-devel'
  when: not is_openjdk_directory.stat.exists
  tags: [ 'jdk' ]

- name: Add path
  become: yes
  become_user: '{{ openjdk.user }}'
  blockinfile:
    path: '~/.bash_profile'
    block: |
      export JAVA_HOME=/usr/lib/jvm/java-{{ openjdk.version }}-openjdk
      export PATH=$PATH:$JAVA_HOME/bin
      export CLASSPATH=.:$JAVA_HOME/jre/lib:$JAVA_HOME/lib:$JAVA_HOME/lib/tools.jar
    marker: '# {mark} ANSIBLE MANAGED BLOCK [JDK]'
  when: not (lookup('file', '~/.bash_profile') is match('^JAVA_HOME.*'))
  tags: [ 'jdk' ]

