---
maven_major: '{{ global_maven.major }}' # Refer to /group_vars/ap-servers
maven_version: '{{ global_maven.version }}' # Refer to /group_vars/ap-servers
maven_basename: 'apache-maven-{{ maven_version }}'
maven_basepath: '/opt/maven'
maven_path: '{{ maven_basepath }}/{{ maven_basename }}'
maven_file: '{{ maven_basename }}-bin.tar.gz'
maven_url: 'http://www.apache.org/dist/maven/maven-{{ maven_major }}/{{ maven_version }}/binaries/{{ maven_file }}'

