---
- name: Check exists JENKINS_HOME
  stat: path='{{ jenkins_home }}'
  register: is_jenkins_home
  tags: [ 'jenkins' ]

- name: Copy Maven configulation file template
  template:
    src: 'hudson.tasks.Maven.xml.j2'
    dest: '{{ jenkins_home }}/hudson.tasks.Maven.xml'
    owner: '{{ jenkins_user }}'
    group: '{{ jenkins_user }}'
    mode: 0644
  when: is_jenkins_home.stat.exists
  tags: [ 'jenkins' ]

- name: Create Jenkins initialize script directory
  file:
    path: '{{ jenkins_home }}/init.groovy.d'
    state: directory
    owner: '{{ jenkins_user }}'
    group: '{{ jenkins_user }}'
    mode: 0755
  when: is_jenkins_home.stat.exists
  tags: [ 'tomcat' ]

- name: Copy Jenkins initialize script template
  template:
    src: 'basic-security.groovy.j2'
    dest: '{{ jenkins_home }}/init.groovy.d/basic-security.groovy'
    owner: '{{ jenkins_user }}'
    group: '{{ jenkins_user }}'
    mode: 0755
  when: is_jenkins_home.stat.exists
  tags: [ 'jenkins' ]

- name: Copy Jenkins backup script
  copy:
    src: 'jenkins-backup.sh'
    dest: '{{ app_bin_path }}/jenkins-backup.sh'
    owner: '{{ jenkins_user }}'
    group: '{{ jenkins_user }}'
    mode: 0755
  when: is_jenkins_home.stat.exists
  tags: [ 'jenkins' ]

- name: Copy Jenkins restore script
  copy:
    src: 'jenkins-restore.sh'
    dest: '{{ app_bin_path }}/jenkins-restore.sh'
    owner: '{{ jenkins_user }}'
    group: '{{ jenkins_user }}'
    mode: 0755
  when: is_jenkins_home.stat.exists
  tags: [ 'jenkins' ]

