---
- name: Get Jenkins crumb
  uri:
    url: '{{ jenkins_url }}/crumbIssuer/api/json'
    user: '{{ jenkins_app_user }}'
    password: '{{ jenkins_app_password }}'
    force_basic_auth: yes
    return_content: yes
  register: crumb_token
  until: crumb_token.content.find('Please wait while Jenkins is getting ready') == -1
  retries: 10
  delay: 5
  tags: [ 'jenkins' ]

- name: Create credentials for Tomcat deploy user
  uri:
    method: POST
    url: '{{ jenkins_url }}/credentials/store/system/domain/_/createCredentials'
    user: '{{ jenkins_app_user }}'
    password: '{{ jenkins_app_password }}'
    force_basic_auth: yes
    headers:
      Jenkins-Crumb: "{{ crumb_token.json.crumb }}"
    status_code: 302
    body: |
      json={
        "": "0",
        "credentials": {
          "scope": "GLOBAL",
          "id": "{{ jenkins_credentials_userid }}",
          "username": "{{ jenkins_credentials_username }}",
          "password": "{{ jenkins_credentials_password }}",
          "description": "{{ jenkins_credentials_description }}",
          "$class": "com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl"
        }
      }
  tags: [ 'jenkins' ]

