---
- name: Check exists jenkins.war
  stat:
    path: '/usr/lib/jenkins/jenkins.war'
  register: is_jenkins
  changed_when: no

- name: Download jenkins.repo
  get_url:
    url: 'https://pkg.jenkins.io/redhat/jenkins.repo'
    dest: '/etc/yum.repos.d/jenkins.repo'
  when: not is_jenkins.stat.exists

- name: Import Jenkins key
  rpm_key:
    state: present
    key: 'https://pkg.jenkins.io/redhat/jenkins.io.key'
  when: not is_jenkins.stat.exists

- name: Install Jenkins
  dnf:
    name: jenkins
    state: latest
  when: not is_jenkins.stat.exists
