---
- name: Check exists jenkins-cli.jar
  stat: path='{{ app_bin_path }}/jenkins-cli.jar'
  register: is_jenkins_cli
  tags: [ 'jenkins' ]

- name: Download jenkins-cli.jar
  get_url:
    url: '{{ jenkins_url }}/jnlpJars/jenkins-cli.jar'
    dest: '{{ app_bin_path }}/jenkins-cli.jar'
    owner: '{{ jenkins_user }}'
    group: '{{ jenkins_user }}'
  when: not is_jenkins_cli.stat.exists
  tags: [ 'jenkins' ]

- name: Install Jenkins plugin
  shell: 'java -jar {{ app_bin_path }}/jenkins-cli.jar -s {{ jenkins_url }} install-plugin {{ item }} --username {{ jenkins_app_user }} --password {{ jenkins_app_password }}'
  with_items:
    # https://plugins.jenkins.io/credentials
    - credentials
    # https://plugins.jenkins.io/git
    - git
    # https://plugins.jenkins.io/deploy
    - deploy
    # https://plugins.jenkins.io/ant
    - ant
  when: not is_jenkins_cli.stat.exists
  tags: [ 'jenkins' ]

- name: Copy Ant plugin configulation file template
  template:
    src: 'hudson.tasks.Ant.xml.j2'
    dest: '{{ jenkins_home }}/hudson.tasks.Ant.xml'
    owner: '{{ jenkins_user }}'
    group: '{{ jenkins_user }}'
    mode: 0644
  tags: [ 'jenkins' ]

