---
- name: Restart Tomcat service
  become: yes
  service:
    name: tomcat
    state: restarted
  tags: [ 'jenkins' ]

- name: Wait untils Tomcat web is available (delay - 30 sec)
  wait_for:
    host: '{{ inventory_hostname }}'
    port: 8080
    state: started
    delay: 30
    connect_timeout: 10
  tags: [ 'jenkins' ]

- name: Wait untils Jenkins web is available (delay - 30 sec)
  uri: url='http://{{ inventory_hostname }}:8080/jenkins/login'
  register: result
  until: result.status == 200
  retries: 7
  delay: 30
  tags: [ 'jenkins' ]

