---
- name: Restart Jenkins service
  become: yes
  service:
    name: jenkins
    state: restarted
  tags: [ 'jenkins' ]

- name: Wait untils Jenkins is available (delay - 30 sec)
  wait_for:
    host: '{{ inventory_hostname }}'
    port: '{{ jenkins_port }}'
    state: started
    delay: 30
    connect_timeout: 10
  tags: [ 'jenkins' ]

- name: Wait untils Jenkins web is available (delay - 30 sec)
  uri: url='{{ jenkins_url }}'
  register: result
  until: result.status == 200
  retries: 7
  delay: 30
  tags: [ 'jenkins' ]

