---
- name: Restart Tomcat service
  become: yes
  systemd:
    name: tomcat
    state: restarted
    enabled: yes

- name: Wait untils Tomcat web is available (delay - 10 sec)
  wait_for:
    host: '{{ inventory_hostname }}'
    port: 8080
    state: started
    delay: 10
    connect_timeout: 18
