---
- name: Check exists application directory
  stat: path='{{ app_home_path }}'
  register: is_app_home_path
  tags: [ 'tomcat' ]

- name: Create Tomcat user
  user: 
    name: '{{ tomcat_user }}'
    password: "{{ tomcat_user_password | password_hash('sha512') }}"
    shell: /bin/bash
    # * Login should be disabled in the production environment.
    #shell: /sbin/nologin
    home: '{{ app_home_path }}'
  tags: [ 'tomcat' ]

- name: Create application source directory
  file:
    path: '{{ app_src_path }}'
    state: directory
    owner: '{{ tomcat_user }}'
    group: '{{ tomcat_user }}'
    mode: 0755
  when: not is_app_home_path.stat.exists
  tags: [ 'tomcat' ]

- name: Create webapps directory
  file:
    path: '{{ app_web_path }}'
    state: directory
    owner: '{{ tomcat_user }}'
    group: '{{ tomcat_user }}'
    mode: 0755
  when: not is_app_home_path.stat.exists
  tags: [ 'tomcat' ]

- name: Create application bin directory
  file:
    path: '{{ app_bin_path }}'
    state: directory
    owner: '{{ tomcat_user }}'
    group: '{{ tomcat_user }}'
    mode: 0755
  when: not is_app_home_path.stat.exists
  tags: [ 'tomcat' ]

- name: Create application config directory
  file:
    path: '{{ app_conf_path }}'
    state: directory
    owner: '{{ tomcat_user }}'
    group: '{{ tomcat_user }}'
    mode: 0755
  when: not is_app_home_path.stat.exists
  tags: [ 'tomcat' ]

- name: Create application data directory
  file:
    path: '{{ app_data_path }}'
    state: directory
    owner: '{{ tomcat_user }}'
    group: '{{ tomcat_user }}'
    mode: 0755
  when: not is_app_home_path.stat.exists
  tags: [ 'tomcat' ]

- name: Create application logs directory
  file:
    path: '{{ app_logs_path }}'
    state: directory
    owner: '{{ tomcat_user }}'
    group: '{{ tomcat_user }}'
    mode: 0755
  when: not is_app_home_path.stat.exists
  tags: [ 'tomcat' ]

- name: Create application temporary directory
  file:
    path: '{{ app_tmp_path }}'
    state: directory
    owner: '{{ tomcat_user }}'
    group: '{{ tomcat_user }}'
    mode: 0755
  when: not is_app_home_path.stat.exists
  tags: [ 'tomcat' ]

