---
- name: Get the latest version number of Maven
  shell: 'curl -Ls {{ maven_url }} | grep -Eo "<a.*>(.*?)<\/a>" | sed -e "s/<[^>]*>//g" | sed "s/\///g" | tail -1'
  register: maven_version
  changed_when: no
  args:
    warn: false

- name: Check exists Maven directory
  stat:
    path: '{{ maven_basepath }}/apache-maven-{{ maven_version.stdout }}'
  register: is_maven
  changed_when: no

- name: Download Maven archive file
  get_url:
    url: '{{ maven_url }}/{{ maven_version.stdout }}/binaries/apache-maven-{{ maven_version.stdout }}-bin.tar.gz'
    dest: '/tmp/apache-maven-{{ maven_version.stdout }}-bin.tar.gz'
    mode: 0644
  when: not is_maven.stat.exists

- name: Create Maven base directory
  file:
    path: '{{ maven_basepath }}'
    state: directory
    mode: 0755
  when: not is_maven.stat.exists

- name: Unarchive Maven archive file
  unarchive:
    src: '/tmp/apache-maven-{{ maven_version.stdout }}-bin.tar.gz'
    dest: '{{ maven_basepath }}'
    mode: 0755
  when: not is_maven.stat.exists

- name: Remove Maven archive file
  file:
    path: '/tmp/apache-maven-{{ maven_version.stdout }}-bin.tar.gz'
    state: absent
  when: not is_maven.stat.exists

- name: Copy maven.sh template
  template:
    src: 'maven.sh.j2'
    dest: '/etc/profile.d/maven.sh'
    mode: 0644
