---
- name: Install desktop environment
  yum: name='{{ item }}' state=present
  with_items:
    - '@Desktop'
    - '@General Purpose Desktop'
  tags: [ 'desktop' ]

- name: Set desktop startup
  lineinfile:
    path: '/etc/inittab'
    state: present
    regexp: '^id:.*'
    line: 'id:5:initdefault:'
  tags: [ 'desktop' ]

