---
- name: Provision all
  hosts: all
  become: yes
  roles:
    - common
    - ssh

- name: Provision development environment
  hosts: development
  become: yes
  roles:
    - desktop
    - xrdp

- name: Provision db-server
  hosts: dbservers
  become: yes
  roles:
    - mysql

- name: Provision ap-server
  hosts: apservers
  become: yes
  roles:
    - user
    - jdk
    - maven
    - tomcat
    - jenkins
    - maildev
    - application
