---
- name: Setup password authentication
  lineinfile:
    path: '/etc/ssh/sshd_config'
    state: present
    regexp: '^PasswordAuthentication .*'
    line: 'PasswordAuthentication yes'

- name: Ssetup port
  lineinfile:
    path: '/etc/ssh/sshd_config'
    state: present
    regexp: '.*Port .*'
    line: 'Port 22'

- name: Restart sshd
  systemd:
    name: sshd
    state: restarted
