---
- name: Install remote desktop
  dnf:
    name: [ 'tigervnc-server', 'xrdp' ]
    state: present
    enablerepo: epel

- name: Enable remote desktop
  systemd:
    name: xrdp
    state: restarted
    enabled: yes
