---
- name: Check exists application
  stat: path={{ app_war_path }}
  register: is_application_file
  tags: [ 'application' ]

- name: Clean application
  become: yes
  become_user: '{{ app_user }}'
  shell: 'mvn clean'
  args:
    chdir: '{{ app_path }}'
  when: not is_application_file.stat.exists
  tags: [ 'application' ]

- name: Compile application
  become: yes
  become_user: '{{ app_user }}'
  shell: 'mvn compile'
  args:
    chdir: '{{ app_path }}'
  when: not is_application_file.stat.exists
  tags: [ 'application' ]

- name: Packaging application
  become: yes
  become_user: '{{ app_user }}'
  shell: 'mvn package'
  args:
    chdir: '{{ app_path }}'
  when: not is_application_file.stat.exists
  tags: [ 'application' ]

