---
- name: Copy deploy-job.xml template
  template:
    src: 'deploy-job.xml.j2'
    dest: '{{ app_data_path }}/deploy-job.xml'
    owner: '{{ tomcat_user }}'
    group: '{{ tomcat_user }}'
    mode: 0644
  tags: [ 'application' ]

- name: Check exists Jenkins job
  shell: 'java -jar {{ app_bin_path }}/jenkins-cli.jar -s http://localhost:8080/jenkins list-jobs --username {{ jenkins_user }} --password {{ jenkins_password }} | grep {{ app_basename }}'
  register: command_result
  failed_when: command_result.rc not in [0, 1]
  tags: [ 'application' ]

- name: Create Jenkins job
  shell: 'java -jar {{ app_bin_path }}/jenkins-cli.jar -s http://localhost:8080/jenkins create-job {{ app_basename }} --username {{ jenkins_user }} --password {{ jenkins_password }} < {{ app_data_path }}/deploy-job.xml'
  when: command_result is success and command_result.rc == 1
  tags: [ 'application' ]

- name: Execute Jenkins job
  shell: 'java -jar {{ app_bin_path }}/jenkins-cli.jar -s http://localhost:8080/jenkins build {{ app_basename }} -s --username {{ jenkins_user }} --password {{ jenkins_password }}'
  tags: [ 'application' ]

