---
- name: Check exists jenkins-cli.jar
  stat:
    path: '{{ apps_bin_path }}/jenkins-cli.jar'
  register: is_jenkins_cli
  changed_when: no

- name: Download jenkins-cli.jar
  get_url:
    url: '{{ jenkins_url }}/jnlpJars/jenkins-cli.jar'
    dest: '{{ apps_bin_path }}/jenkins-cli.jar'
    owner: '{{ apps_user }}'
    group: '{{ apps_group }}'
  when: not is_jenkins_cli.stat.exists

- name: Check exists Jenkins job.
  shell: 'java -jar {{ apps_bin_path }}/jenkins-cli.jar -s {{ jenkins_url }} -auth {{ jenkins_app_user }}:{{ jenkins_app_pass }} list-jobs | grep {{ app_basename }}'
  register: command_result
  changed_when: no
  failed_when: command_result.rc not in [0, 1]

- name: Copy build-job.xml template
  template:
    src: 'build-job.xml.j2'
    dest: '{{ apps_data_path }}/build-job.xml'
    owner: '{{ apps_user }}'
    group: '{{ apps_group }}'
    mode: 0644
  when: command_result is success and command_result.rc == 1

- name: Create Jenkins job
  shell: 'java -jar {{ apps_bin_path }}/jenkins-cli.jar -s {{ jenkins_url }} -auth {{ jenkins_app_user }}:{{ jenkins_app_pass }} create-job {{ app_basename }} < {{ apps_data_path }}/build-job.xml'
  when: command_result is success and command_result.rc == 1

- name: Run Jenkins job
  shell: 'java -jar {{ apps_bin_path }}/jenkins-cli.jar -s {{ jenkins_url }} -auth {{ jenkins_app_user }}:{{ jenkins_app_pass }} build {{ app_basename }}'
  when: command_result is success and command_result.rc == 1
