---
- name: Check exists application sources
  stat:
    path: '{{ app_sources_path }}'
  register: is_application_sources
  changed_when: no

- name: Download application from repository
  become: yes
  become_user: '{{ apps_user }}'
  git: 
    repo: '{{ app_repository_url }}'
    dest: '{{ app_sources_path }}'
  when: not is_application_sources.stat.exists
