---
- name: Check exists Apache Ant directory
  stat: path='{{ ant_path }}'
  register: is_ant
  tags: [ 'ant' ]

- name: Download Apache Ant archive file
  get_url:
    url: '{{ ant_url }}'
    dest: '/tmp/{{ ant_file }}'
    mode: 0644
  when: not is_ant.stat.exists
  tags: [ 'ant' ]

- name: Create Apache Ant base directory
  file:
    path: '{{ ant_basepath }}'
    state: directory
    mode: 0755
  when: not is_ant.stat.exists
  tags: [ 'ant' ]

- name: Install Apache Ant
  unarchive:
    src: '/tmp/{{ ant_file }}'
    dest: '{{ ant_basepath }}'
    mode: 0755
  when: not is_ant.stat.exists
  tags: [ 'ant' ]

- name: Remove Apache Ant archive file
  file:
    path: '/tmp/{{ ant_file }}'
    state: absent
  when: not is_ant.stat.exists
  tags: [ 'ant' ]

- name: Copy ant.sh template
  template:
    src: 'ant.sh.j2'
    dest: '/etc/profile.d/ant.sh'
    mode: 0644
  tags: [ 'ant' ]

