---
- name: Check exists application directory
  stat:
    path: '{{ apps_home_path }}'
  register: is_apps_home_path
  changed_when: no

- name: Create application group
  group:
    name: '{{ apps_group }}'
  when: not is_apps_home_path.stat.exists

- name: Create application user
  user:
    name: '{{ apps_user }}'
    password: "{{ apps_user_password | password_hash('sha512') }}"
    group: '{{ apps_group }}'
    home: '{{ apps_home_path }}'
    shell: /bin/bash
    #shell: /sbin/nologin
  when: not is_apps_home_path.stat.exists

- name: Create application home directories
  file:
    path: '{{ item }}'
    state: directory
    owner: '{{ apps_user }}'
    group: '{{ apps_group }}'
    mode: 0775
  loop:
     - '{{ apps_home_path }}'
     - '{{ apps_src_path }}'
     - '{{ apps_web_path }}'
     - '{{ apps_bin_path }}'
     - '{{ apps_conf_path }}'
     - '{{ apps_data_path }}'
     - '{{ apps_logs_path }}'
  when: not is_apps_home_path.stat.exists
